# Generated by Django 5.2.12 on 2026-04-01 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_summarizeddocument_content_hash_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedmaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='shared_files/'),
        ),
        migrations.CreateModel(
            name='KnownIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_ips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
