# Generated by Django 5.2.12 on 2026-04-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sharedmaterial_file_knownip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarizeddocument',
            old_name='period',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='sharedmaterial',
            name='period',
        ),
        migrations.RemoveField(
            model_name='task',
            name='period',
        ),
        migrations.AddField(
            model_name='sharedmaterial',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Shared Resource', 'Shared Resource'), ('Discussion', 'Discussion'), ('Revision', 'Review')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Project', 'Project'), ('Research', 'Research'), ('Revision', 'Revision')], default='General', max_length=20),
        ),
    ]
