# Generated by Django 5.2.12 on 2026-04-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_scheduleitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedmaterial',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
