# Generated by Django 5.2.12 on 2026-04-06 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sharedmaterial_is_anonymous'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedmaterial',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedmaterial',
            name='period',
            field=models.CharField(choices=[('General', 'General'), ('Prelims', 'Prelims'), ('Midterms', 'Midterms'), ('Finals', 'Finals')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='summarizeddocument',
            name='period',
            field=models.CharField(default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='period',
            field=models.CharField(choices=[('General', 'General'), ('Prelims', 'Prelims'), ('Midterms', 'Midterms'), ('Finals', 'Finals')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='No bio yet... ✍️', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='Focus Room 📚', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, default='General Studies 🎓', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
