# Generated by Django 5.2.12 on 2026-04-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_summarizeddocument_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedmaterial',
            name='is_removed_by_mod',
            field=models.BooleanField(default=False),
        ),
    ]
