# Generated by Django 5.2.12 on 2026-04-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_sharedmaterial_is_removed_by_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedmaterial',
            name='file_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedmaterial',
            name='file_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
