# Generated by Django 5.2.12 on 2026-04-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sharedmaterial_file_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarizeddocument',
            name='file_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarizeddocument',
            name='file_mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
