# Generated by Django 5.2.12 on 2026-04-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_mastered',
            field=models.BooleanField(default=False, help_text='Passed with 80% or higher'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='reflection',
            field=models.TextField(blank=True, help_text='Mandatory learning proof for badges', null=True),
        ),
    ]
